# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/storage_check',
                'doc_host': 'https://sfc-gh-jdemlow.github.io',
                'git_url': 'https://github.com/sfc-gh-jdemlow/storage_check',
                'lib_path': 'storage_check'},
  'syms': {'storage_check.core': {'storage_check.core.foo': ('core.html#foo', 'storage_check/core.py')}}}
